# gunpun-server-game-staging -> <your_app_name>

steps:
  - name: "gcr.io/cloud-builders/docker"
    env: ["ENV=staging"]
    args: ["build", "-t", "vonicvn/gunpun-server-game-staging:$REVISION_ID", "."]

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args: [ '-c', 'gcloud secrets versions access latest --secret=dockerhub-vonicvn > decrypted-data.txt' ]

  - name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args: ["-c", "docker login --username=vonicvn --password-stdin < decrypted-data.txt"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "vonicvn/gunpun-server-game-staging:$REVISION_ID"]

  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "compute","ssh","jasontran@services","--zone=asia-southeast1-b","--force-key-file-overwrite",
        "--command=docker pull vonicvn/gunpun-server-game-staging:$REVISION_ID && docker service update gunpun-server-game-staging_app --image vonicvn/gunpun-server-game-staging:$REVISION_ID"
      ]
timeout: 1800s